name: 'Deploy to Hosting'
on:
  push:
    branches:
      - main # или ваша основная ветка
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # укажите версию Node.js

      - name: Install dependencies
        run: sudo npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Hosting
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          apt-get install -y lftp
          lftp -f "
          open $FTP_SERVER
          user $FTP_USERNAME $FTP_PASSWORD
          mirror -R build/ /path/to/your/web/root/
          bye
          "
